[package]
name = "platformer-ldtk"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.1"
bevy_ecs_ldtk = "0.11.0"
bevy_rapier2d = "0.28.0"
bevy-parallax = { git = "https://github.com/Corrosive-Games/bevy-parallax.git", tag = "v0.11.0" }
